### ISSUE TITLE
Delete this repo

### ISSUE THREAD

**Issue by alwins0n** [vavr-io/vavr-jdbi#1]
As discussed this module repo could be deleted.

It would be nice to add a section to the vavr.io page about third party libs that support vavr. I.e. ppl should know that there is for example a jdbc library such as jdbi out there that supports vavr return types and so on.

If this happens there is no need for this module to exist

**Comment by danieldietrich** [comment]
Thx for the hint, I will delete this repo now.

I like the idea of pointing to libraries that support VAVR. I created an issue: vavr-io/vavr-io.github.io#10
